package br.com.caelum.estoque.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2020-04-15T23:07:28.167-03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AutorizacaoFault", targetNamespace = "http://ws.estoque.caelum.com.br/")
public class AutorizacaoFault extends Exception {
	private static final long serialVersionUID = -1974179416747904050L;
	
	private String autorizacaoFault;

    public AutorizacaoFault() {
        super();
    }
    
    public AutorizacaoFault(String message) {
        super(message);
    }
    
    public AutorizacaoFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AutorizacaoFault(String message, String autorizacaoFault) {
        super(message);
        this.autorizacaoFault = autorizacaoFault;
    }

    public AutorizacaoFault(String message, String autorizacaoFault, Throwable cause) {
        super(message, cause);
        this.autorizacaoFault = autorizacaoFault;
    }

    public String getFaultInfo() {
        return this.autorizacaoFault;
    }
}
